DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `posts`;
DROP TABLE IF EXISTS `posts_tags`;

CREATE TABLE tags (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(50) UNIQUE NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE posts (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(50) UNIQUE NOT NULL,
  `body` TEXT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `publish` DATE NULL,
  `user_id` INTEGER NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES users (`id`)
);


CREATE TABLE posts_tags (
  `post_id` INTEGER NOT NULL,
  `tag_id` INTEGER NOT NULL,
  FOREIGN KEY (`post_id`) REFERENCES posts (`id`),
  FOREIGN KEY (`tag_id`) REFERENCES tags (`id`)
);